services:
#    recensement.example:
#        class: Recensement\RecensementBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    redirectionListener:
      class: Recensement\RecensementBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }