<?php
namespace Utilisateurs\UtilisateursBundle\Entity;

use FOS\UserBundle\Model\GroupInterface;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="utilisateurs")
 */
class Utilisateurs extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
    }

    public function addRole($role)
    {
        return parent::addRole($role); // TODO: Change the autogenerated stub
    }

    public function serialize()
    {
        return parent::serialize(); // TODO: Change the autogenerated stub
    }

    public function unserialize($serialized)
    {
        parent::unserialize($serialized); // TODO: Change the autogenerated stub
    }

    public function eraseCredentials()
    {
        parent::eraseCredentials(); // TODO: Change the autogenerated stub
    }

    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function getUsername()
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }

    public function getUsernameCanonical()
    {
        return parent::getUsernameCanonical(); // TODO: Change the autogenerated stub
    }

    public function getSalt()
    {
        return parent::getSalt(); // TODO: Change the autogenerated stub
    }

    public function getEmail()
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }

    public function getEmailCanonical()
    {
        return parent::getEmailCanonical(); // TODO: Change the autogenerated stub
    }

    public function getPassword()
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    public function getPlainPassword()
    {
        return parent::getPlainPassword(); // TODO: Change the autogenerated stub
    }

    public function getLastLogin()
    {
        return parent::getLastLogin(); // TODO: Change the autogenerated stub
    }

    public function getConfirmationToken()
    {
        return parent::getConfirmationToken(); // TODO: Change the autogenerated stub
    }

    public function getRoles()
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }

    public function hasRole($role)
    {
        return parent::hasRole($role); // TODO: Change the autogenerated stub
    }

    public function isAccountNonExpired()
    {
        return parent::isAccountNonExpired(); // TODO: Change the autogenerated stub
    }

    public function isAccountNonLocked()
    {
        return parent::isAccountNonLocked(); // TODO: Change the autogenerated stub
    }

    public function isCredentialsNonExpired()
    {
        return parent::isCredentialsNonExpired(); // TODO: Change the autogenerated stub
    }

    public function isCredentialsExpired()
    {
        return parent::isCredentialsExpired(); // TODO: Change the autogenerated stub
    }

    public function isEnabled()
    {
        return parent::isEnabled(); // TODO: Change the autogenerated stub
    }

    public function isExpired()
    {
        return parent::isExpired(); // TODO: Change the autogenerated stub
    }

    public function isLocked()
    {
        return parent::isLocked(); // TODO: Change the autogenerated stub
    }

    public function isSuperAdmin()
    {
        return parent::isSuperAdmin(); // TODO: Change the autogenerated stub
    }

    public function removeRole($role)
    {
        return parent::removeRole($role); // TODO: Change the autogenerated stub
    }

    public function setUsername($username)
    {
        return parent::setUsername($username); // TODO: Change the autogenerated stub
    }

    public function setUsernameCanonical($usernameCanonical)
    {
        return parent::setUsernameCanonical($usernameCanonical); // TODO: Change the autogenerated stub
    }

    public function setCredentialsExpireAt(\DateTime $date = null)
    {
        return parent::setCredentialsExpireAt($date); // TODO: Change the autogenerated stub
    }

    public function setCredentialsExpired($boolean)
    {
        return parent::setCredentialsExpired($boolean); // TODO: Change the autogenerated stub
    }

    public function setEmail($email)
    {
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    public function setEmailCanonical($emailCanonical)
    {
        return parent::setEmailCanonical($emailCanonical); // TODO: Change the autogenerated stub
    }

    public function setEnabled($boolean)
    {
        return parent::setEnabled($boolean); // TODO: Change the autogenerated stub
    }

    public function setExpired($boolean)
    {
        return parent::setExpired($boolean); // TODO: Change the autogenerated stub
    }

    public function setExpiresAt(\DateTime $date = null)
    {
        return parent::setExpiresAt($date); // TODO: Change the autogenerated stub
    }

    public function setPassword($password)
    {
        return parent::setPassword($password); // TODO: Change the autogenerated stub
    }

    public function setSuperAdmin($boolean)
    {
        return parent::setSuperAdmin($boolean); // TODO: Change the autogenerated stub
    }

    public function setPlainPassword($password)
    {
        return parent::setPlainPassword($password); // TODO: Change the autogenerated stub
    }

    public function setLastLogin(\DateTime $time = null)
    {
        return parent::setLastLogin($time); // TODO: Change the autogenerated stub
    }

    public function setLocked($boolean)
    {
        return parent::setLocked($boolean); // TODO: Change the autogenerated stub
    }

    public function setConfirmationToken($confirmationToken)
    {
        return parent::setConfirmationToken($confirmationToken); // TODO: Change the autogenerated stub
    }

    public function setPasswordRequestedAt(\DateTime $date = null)
    {
        return parent::setPasswordRequestedAt($date); // TODO: Change the autogenerated stub
    }

    public function getPasswordRequestedAt()
    {
        return parent::getPasswordRequestedAt(); // TODO: Change the autogenerated stub
    }

    public function isPasswordRequestNonExpired($ttl)
    {
        return parent::isPasswordRequestNonExpired($ttl); // TODO: Change the autogenerated stub
    }

    public function setRoles(array $roles)
    {
        return parent::setRoles($roles); // TODO: Change the autogenerated stub
    }

    public function getGroups()
    {
        return parent::getGroups(); // TODO: Change the autogenerated stub
    }

    public function getGroupNames()
    {
        return parent::getGroupNames(); // TODO: Change the autogenerated stub
    }

    public function hasGroup($name)
    {
        return parent::hasGroup($name); // TODO: Change the autogenerated stub
    }

    public function addGroup(GroupInterface $group)
    {
        return parent::addGroup($group); // TODO: Change the autogenerated stub
    }

    public function removeGroup(GroupInterface $group)
    {
        return parent::removeGroup($group); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }


}