<?php


namespace Recensement\RecensementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HabitantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitantsRepository extends EntityRepository
{
    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.prenom like :chaine')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }

    public function supprimer($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.nom like :chaine')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }

    public function byDate()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.dateEnregistrement', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
