<?php

namespace Recensement\RecensementBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ThouarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThouarsRepository extends EntityRepository
{
}
