admin:
    path:     /
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:index" }

admin_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:show" }

admin_new:
    path:     /new
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:new" }

admin_create:
    path:     /create
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:create" }
    requirements: { _method: post }

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:edit" }

admin_update:
    path:     /{id}/update
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:update" }
    requirements: { _method: post|put }

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateursBundle:Utilisateurs:delete" }
    requirements: { _method: post|delete }
